version: 2

defaults: &defaults
  working_directory: ~/project/padoc
  docker:
    - image: labeldock/circleci-node:8.11

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: npm module
          command: npm install
      - persist_to_workspace:
          root: ~/project
          paths:
            - padoc
  
  compile:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: COMPILE
          command: npm run test:compile -s
      - run:
          name: Result tree
          command: tree sample

  compile-umd:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: COMPILE
          command: npm run test:compile -- -m umd -s
      - run:
          name: Result tree
          command: tree sample

  compile-cjs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: COMPILE
          command: npm run test:compile -- -m cjs -s
      - run:
          name: Result tree
          command: tree sample

  compile-amd:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: COMPILE
          command: npm run test:compile -- -m amd -s
      - run:
          name: Result tree
          command: tree sample

  pack-umd:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: COMPILE
          command: npm run test:pack -- -m umd -s
      - run:
          name: Result tree
          command: tree sample

  pack-cjs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: COMPILE
          command: npm run test:pack -- -m cjs -s
      - run:
          name: Result tree
          command: tree sample

  pack-amd:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: COMPILE
          command: npm run test:pack -- -m amd -s
      - run:
          name: Result tree
          command: tree sample

  pack-iife:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: COMPILE
          command: npm run test:pack -- -m iife -s
      - run:
          name: Result tree
          command: tree sample

  pack-iife-name:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: COMPILE
          command: npm run test:pack -- -m iife -n packs -s
      - run:
          name: Result tree
          command: tree sample

  result:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Badge success
          command: cat package.json

workflows:
  version: 2
  task:
    jobs:
      - build
      - compile:
          requires:
            - build
      - compile-umd:
          requires:
            - build
      - compile-cjs:
          requires:
            - build
      - compile-amd:
          requires:
            - build
      - pack-umd:
          requires:
            - build
      - pack-cjs:
          requires:
            - build
      - pack-amd:
          requires:
            - build
      - pack-iife:
          requires:
            - build
      - pack-iife-name:
          requires:
            - build
      - result:
          requires:
            - compile-umd
            - compile-cjs
            - compile-amd
            - pack-umd
            - pack-cjs
            - pack-amd
            - pack-iife
            - pack-iife-name